[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false


[[redirects]]
  from = "https://mellifluous-fudge-1ff812.netlify.app"
  to = "https://thesmmgal.net"
  status = 301
  force = true
