[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false


[[redirects]]
  from = "/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fcoach_ras%2Fedit-and-rewrite-your-resume-cover-letter-and-linkedin-fast"
  status = 301
  force = true

[[redirects]]
  from = "/1/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dtheory%2520assignment%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dtheory%2520assignment"
  status = 301
  force = true


[[redirects]]
  from = "/2/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dpython%2520assignment%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dpython%2520assignment"
  status = 301
  force = true

[[redirects]]
  from = "/3/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dmonte%2520carlo%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dmonte%2520carlo"
  status = 301
  force = true
  
  
  [[redirects]]
  from = "/4/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3DInterior%2520Design%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dinterior%2520design"
  status = 301
  force = true


  [[redirects]]
  from = "/5/"
  to = "https://www.fiverr.com/search/gigs?query=virtual%20assistant&source=top-bar&search_in=everywhere&search-autocomplete-original-term=virtual%20assistant"
  status = 301
  force = true

  [[redirects]]
  from = "/6/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dgraphic%2520artist%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dgraphic%2520artist"
  status = 301
  force = true

  [[redirects]]
  from = "/7/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dspanish%2520translator%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dspanish%2520translator"
  status = 301
  force = true
  
  [[redirects]]
  from = "/8/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dmusic%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dmusic"
  status = 301
  force = true

 [[redirects]]
  from = "/9/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dpower%2520bi%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dpower%2520bi"
  status = 301
  force = true
  
  [[redirects]]
  from = "/10/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dcaricature%2520painting%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dcaricature%2520painting"
  status = 301
  force = true

[[redirects]]
  from = "/11/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dcontent%2520creators%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dcontent%2520creators"
  status = 301
  force = true
  
  [[redirects]]
  from = "/12/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3DYoutube%2520script%2520writer%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dyoutube%2520script%2520writer"
  status = 301
  force = true
  
  [[redirects]]
  from = "/13/"
  to = "https://www.fiverr.com/search/gigs?query=film%20sound&source=top-bar&search_in=everywhere&search-autocomplete-original-term=film%20sound"
  status = 301
  force = true
