[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false


[[redirects]]
  from = "/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fcoach_ras%2Fedit-and-rewrite-your-resume-cover-letter-and-linkedin-fast"
  status = 301
  force = true

[[redirects]]
  from = "/1/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dtheory%2520assignment%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dtheory%2520assignment"
  status = 301
  force = true


[[redirects]]
  from = "/2/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dpython%2520assignment%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dpython%2520assignment"
  status = 301
  force = true

[[redirects]]
  from = "/3/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dmonte%2520carlo%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dmonte%2520carlo"
  status = 301
  force = true
  
  
  [[redirects]]
  from = "/4/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3DInterior%2520Design%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dinterior%2520design"
  status = 301
  force = true


  [[redirects]]
  from = "/5/"
  to = "https://www.fiverr.com/search/gigs?query=virtual%20assistant&source=top-bar&search_in=everywhere&search-autocomplete-original-term=virtual%20assistant"
  status = 301
  force = true

  [[redirects]]
  from = "/6/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dgraphic%2520artist%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dgraphic%2520artist"
  status = 301
  force = true

  [[redirects]]
  from = "/7/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dspanish%2520translator%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dspanish%2520translator"
  status = 301
  force = true
  
  [[redirects]]
  from = "/8/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dmusic%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dmusic"
  status = 301
  force = true

 [[redirects]]
  from = "/9/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dpower%2520bi%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dpower%2520bi"
  status = 301
  force = true
  
  [[redirects]]
  from = "/10/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dcaricature%2520painting%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dcaricature%2520painting"
  status = 301
  force = true

[[redirects]]
  from = "/11/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dcontent%2520creators%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dcontent%2520creators"
  status = 301
  force = true
  
  [[redirects]]
  from = "/12/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3DYoutube%2520script%2520writer%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dyoutube%2520script%2520writer"
  status = 301
  force = true
  
  [[redirects]]
  from = "/13/"
  to = "https://www.fiverr.com/search/gigs?query=film%20sound&source=top-bar&search_in=everywhere&search-autocomplete-original-term=film%20sound"
  status = 301
  force = true

  [[redirects]]
  from = "/14/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dwall%2520paper%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dwall%2520paper"
  status = 301
  force = true
  
  [[redirects]]
  from = "/15/"
  to = "https://87d50lt9tofz1x0gsgoax3nc4j.hop.clickbank.net/?tid=1"
  status = 301
  force = true
  
  [[redirects]]
  from = "/16/"
  to = "https://www.fiverr.com/search/gigs?query=tax%20for%20freelancer&source=top-bar&search_in=everywhere&search-autocomplete-original-term=tax%20for%20freelancer"
  status = 301
  force = true

  [[redirects]]
  from = "/17/"
  to = "https://3536fhj6xms00-40fnjhbkes1d.hop.clickbank.net/?tid=2"
  status = 301
  force = true

  [[redirects]]
  from = "/18/"
  to = "https://eca54lgzsgi2uu2b52h6fwep7f.hop.clickbank.net/?tid=3"
  status = 301
  force = true
  
  [[redirects]]
  from = "/19/"
  to = "https://9e8d0efcncjy7x6m38r9e6v94i.hop.clickbank.net/?tid=4"
  status = 301
  force = true
  
  [[redirects]]
  from = "/20/"
  to = "https://4edd8pt-mdr911vaf9snv2oz9k.hop.clickbank.net/?tid=5"
  status = 301
  force = true
  
  [[redirects]]
  from = "/21/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dshoppy%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dshoppy"
  status = 301
  force = true
  
  [[redirects]]
  from = "/22/"
  to = "https://677dbin7ofl-3zy0uqyikdenc7.hop.clickbank.net/?tid=6"
  status = 301
  force = true
 
  [[redirects]]
  from = "/23/"
  to = "https://b7478fn4womz8tzr1wbhfmeof5.hop.clickbank.net/?tid=7"
  status = 301
  force = true

  [[redirects]]
  from = "/24/"
  to = "https://f0e70et2xet9ws-gohwy-mkp1x.hop.clickbank.net/?tid=8"
  status = 301
  force = true

  [[redirects]]
  from = "/25/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsidrajb%2Fmake-forrest-plots-for-you"
  status = 301
  force = true

  [[redirects]]
  from = "/26/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fprosanto7%2Fdo-java-project-java-assignment-and-java-swing-task-using-netbeans-intellij"
  status = 301
  force = true

  [[redirects]]
  from = "/27/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fmegmarmed%2Fhelp-you-understand-your-medical-records-or-results"
  status = 301
  force = true
  
  [[redirects]]
  from = "/28/"
  to = "https://fa3cbbh3yor7515709ze3gdl5y.hop.clickbank.net/?tid=9"
  status = 301
  force = true
  
  [[redirects]]
  from = "/29/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fbeforeverly%2Fwrite-a-custom-job-offer-letter-for-you"
  status = 301
  force = true

  [[redirects]]
  from = "/30/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsazrah4life%2Frecord-your-female-voice-over-with-british-accent"
  status = 301
  force = true

  [[redirects]]
  from = "/31/"
  to = "https://6f348qpbqgs8v5-osancke313f.hop.clickbank.net/?tid=10"
  status = 301
  force = true

  [[redirects]]
  from = "/32/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsajjadahmad384%2Fcreate-excel-graphs-pivot-tables-dashboards-and-macros"
  status = 301
  force = true

  [[redirects]]
  from = "/33/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dcontent%2520creation%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dcontent%2520creation"
  status = 301
  force = true

  [[redirects]]
  from = "/34/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dflag%2520design%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dflag%2520design"
  status = 301
  force = true
  
  [[redirects]]
  from = "/35/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dvoice%2520actor%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dvoice%2520actor"
  status = 301
  force = true

  [[redirects]]
  from = "/36/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dradiant%2520coaching%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dradiant%2520coaching"
  status = 301
  force = true
  
  [[redirects]]
  from = "/37/"
  to = "https://amzn.to/3nEVJDu"
  status = 301
  force = true
  
  [[redirects]]
  from = "/38/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dsims%25204%2520mod%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dsims%25204%2520mod"
  status = 301
  force = true

  [[redirects]]
  from = "/39/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dtwitch%2520logo%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dtwitch%2520logo"
  status = 301
  force = true
  
  [[redirects]]
  from = "/40/"
  to = "https://amzn.to/3aezssZ"
  status = 301
  force = true
  
  [[redirects]]
  from = "/41/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dresume%2520writing%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dresume%2520writing"
  status = 301
  force = true

  [[redirects]]
  from = "/42/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fnwcoast90%2Ftranslate-japanese-to-english-or-english-to-japanese-7960"
  status = 301
  force = true

  [[redirects]]
  from = "/43/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fexpert_arbaz%2Fwrite-veterinary-and-pets-articles-and-blogposts"
  status = 301
  force = true

  [[redirects]]
  from = "/44/"
  to = "https://amzn.to/3RlwHaa"
  status = 301
  force = true

  [[redirects]]
  from = "/45/"
  to = "https://259c6dp7rqq6y469356nfr6k7k.hop.clickbank.net/?tid=11"
  status = 301
  force = true

  [[redirects]]
  from = "/46/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dhealth%2520writer%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dhealth%2520writer"
  status = 301
  force = true

  [[redirects]]
  from = "/47/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dmath%2520tutor%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dmath%2520tutor"
  status = 301
  force = true

  [[redirects]]
  from = "/48/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dshopify%2520website%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dshopify%2520website"
  status = 301
  force = true

  [[redirects]]
  from = "/49/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dessay%2520writing%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dessay%2520writing"
  status = 301
  force = true

  [[redirects]]
  from = "/50/"
  to = "https://amzn.to/3yRm47T"
  status = 301
  force = true

  [[redirects]]
  from = "/51/"
  to = "https://5dac7qnzthq-0222ggipuev03x.hop.clickbank.net/?tid=12"
  status = 301
  force = true

  [[redirects]]
  from = "/52/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dubuntu%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dubuntu"
  status = 301
  force = true

  [[redirects]]
  from = "/53/"
  to = "https://amzn.to/3umxRbC"
  status = 301
  force = true

  [[redirects]]
  from = "/54/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dillustrator%2520tutor%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dillustrator%2520tutor"
  status = 301
  force = true

  [[redirects]]
  from = "/55/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Dmoroccan%2520dialect%2520tutor%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Dmoroccan%2520dialect%2520tutor"
  status = 301
  force = true

  [[redirects]]
  from = "/56/"
  to = "https://59086gqbtjh9zy5csfoco4sr6f.hop.clickbank.net/?tid=1"
  status = 301
  force = true

  [[redirects]]
  from = "/57/"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fsearch%2Fgigs%3Fquery%3Daudio%2520engineer%26source%3Dtop-bar%26search_in%3Deverywhere%26search-autocomplete-original-term%3Daudio%2520engineer"
  status = 301
  force = true

  [[redirects]]
  from = "/58/"
  to = "https://amzn.to/3TP28uM"
  status = 301
  force = true
  
  [[redirects]]
  from = "/59/"
  to = "https://amzn.to/3TP6D8E"
  status = 301
  force = true
 
  [[redirects]]
  from = "/60/"
  to = "https://amzn.to/3etscLM"
  status = 301
  force = true

  [[redirects]]
  from = "/61/"
  to = "https://amzn.to/3KVyG20"
  status = 301
  force = true

  [[redirects]]
  from = "/62/"
  to = "https://amzn.to/3AXnnSq"
  status = 301
  force = true

  [[redirects]]
  from = "/63/"
  to = "https://amzn.to/3Qyg2OV"
  status = 301
  force = true
 
  [[redirects]]
  from = "/64/"
  to = "https://amzn.to/3Di8soN"
  status = 301
  force = true

  [[redirects]]
  from = "/65/"
  to = "https://amzn.to/3TUK8it"
  status = 301
  force = true

  [[redirects]]
  from = "/66/"
  to = "https://amzn.to/3ezTmk0"
  status = 301
  force = true
  
  [[redirects]]
  from = "/67/"
  to = "https://amzn.to/3RwRRl3"
  status = 301
  force = true
  
  [[redirects]]
  from = "/68/"
  to = "https://amzn.to/3etDsYk"
  status = 301
  force = true
