[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false


[[redirects]]
  from = "/*"
  to = "https://go.fiverr.com/visit/?bta=456298&brand=fiverrcpa&landingPage=https%3A%2F%2Fwww.fiverr.com%2Fdavidquintanaw%2Fdense-memes-for-your-site"
  status = 301
  force = true
